config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  root 'home#page'
  patch '/jobs/:id/update', to: 'jobs#update_job', as: 'update_job'
  resources :jobs do
    resources :reviews
  end
  devise_for :users
  get '/profile/:id', to: 'profile#page', as: 'profile_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  # double relationship references for user table
  belongs_to :tradie, class_name: 'User', optional: true
  belongs_to :homeowner, class_name: 'User'

  # enables many files to be attached and associated with the job model
  has_many_attached :photos

  # enables many job completion files to be attached and associated with the job model
  has_many_attached :completion_photos

  # enables one quote file to be attached
  has_one_attached :quote

  # allows a job to have many reviews
  has_many :reviews

  # Enums for status variable (open, active, closed)
  # job.status_active?    # Returns true if job.status == 'active'
  # job.status_open!      # same as job.update(status: :open)
  # job.status_closed     # Job.where(status: :closed)
  enum status: {
    open: 0,
    active: 1,
    verified: 2,
    finished: 3,
    sent: 4,
    closed: 5,
    cancelled: 6
  }, _prefix: true

  # gets the full address
  def full_address
    "#{street_address} #{suburb.capitalize} #{postcode} #{state} "
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy update_job user_reviews]
  before_action :set_job, only: %i[show edit update destroy update_job user_reviews]
  before_action :check_user, only: [:show]
  before_action :check_ownership, only: %i[edit update update_job destroy]
  before_action :user_reviews, only: [:show]

  # GET /jobs or /jobs.json
  def index
    # this checks if the current user is a tradie
    @jobs = if current_user.tradie
              # this selects only jobs that belong to the current user (tradie)
              Job.all.select { |job| job.tradie_id == current_user.id }
            else
              # this selects only jobs that belong to the current user (homeowner)
              Job.all.select { |job| job.homeowner_id == current_user.id }
            end
  end

  # GET /jobs/1 or /jobs/1.json
  def show; end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    # sets the job owner to the current user(homeowner)
    @job.homeowner_id = current_user.id

    respond_to do |format|
      # if save is successful
      if @job.save
        format.html { redirect_to job_url(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      # this checks if the update was successful
      if @job.update(job_params)
        # if the job status is active and the current user is a tradie
        if @job.status_active? && current_user.tradie?
          # sets the current user(tradie) as the tradie of the job once they submit a quote
          @job.update(tradie_id: current_user.id)
        end
        format.html { redirect_to job_url(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_job
    # if job_update was successful
    if @job.update(status: params[:status])
      redirect_to job_url(@job), alert: 'Job was cancelled.'
    else
      redirect_to jobs_url, alert: 'Job was not cancelled, please try again.'
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # checks is current user has left a review
  def user_reviews
    if user_signed_in?
      @user_reviews = 0
      @job.reviews.each do |review|
        # if current user has left a review
        @user_reviews += 1 if current_user.id == review.user_id
      end
    end
  end

  private

  # sets the job
  def set_job
    @job = Job.find(params[:id])
  end

  # Only allow a list of trusted parameters through
  def job_params
    params.require(:job).permit(:title, :description, :street_address, :suburb, :postcode, :state, :price, :status,
                                :successful, :paid_on_time, :payment_terms, :quote, photos: [], completion_photos: [])
  end

  # checks if the user can view a job that is not open or successful on the public show page
  def check_user
    # if the job is not open and not successful
    if !@job.status_open? && !@job.successful
      if current_user.tradie?
        # if the current user is not the job tradie
        redirect_to root_url, alert: 'You do not have access to that job' if current_user.id != @job.tradie_id
      elsif current_user.id != @job.homeowner_id
        # if current user is not the job homeowner
        redirect_to root_url, alert: 'You do not have access to that job'
      end
    end
  end

  # checks if a user owns the job before editing, updating or deleting
  def check_ownership
    if current_user.tradie?
      # if the current user is not the job tradie
      redirect_to root_url, alert: 'You do not have access to that job' if !@job.status_open? &&current_user.id != @job.tradie_id
    elsif current_user.id != @job.homeowner_id
      # if current user is not the job homeowner
      redirect_to root_url, alert: 'You do not have access to that job'
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%# if the current user is logged in and not a tradie %>
    <% if current_user.id? && !current_user.tradie? %>
      
      <%# when the job status is set to open %>
      <% if @job.status_open? %>
        <%# If no existing job title %>
        <% if @job.title == nil %>
          <h1>Create Job: <%= @job.title %></h1>
        <% else %>
          <h1>Edit Job: <%= @job.title %></h1>
        <% end %>
        <%= f.input :title, required: true, label: "Short and sweet, ie - Kitchen Reno" %>
        <%= f.input :description, required: true %>
        <%= f.input :street_address, required: true %>
        <%= f.input :suburb, required: true %>
        <%= f.input :postcode, required: true %>
        <%= f.input :state, required: true, collection: ["QLD", "NT", "WA", "NSW", "ACT", "VIC", "SA", "TAS"] %>
        <%= f.input :price, required: false %>
        <%= f.input :payment_terms, collection: 7..30, label: 'Payment Terms (default: 7 days to make payment once job is completed)' %>
        <br>
        <p>Upload photos of the job here (you must upload at least one photo to the job)</p>
        <%# allows the user to upload multiple files %>
        <%= f.file_field :photos, required: true, multiple: true, accept: "image/png, image/jpg, image/jpeg, image/pdf", class: "form-control" %><br>
        <p><strong>*Required Fields</strong></p>
        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>

      <%# when the job status is set to active %>
      <% elsif @job.status_active? %>
        <h1>Verify Funds: <%= @job.title %></h1>
        <p>Once you verify your funds with PayProof, the tradie can start the job.</p>
        <p><strong>*By verifying your funds, you are confirming that you agree to the tradies quote and the payment terms of <%= @job.payment_terms %> days. This means that you have <%= @job.payment_terms %> days to send payment once the tradie has marked the job as complete.</strong></p>
        <%= f.input :status, :as => :hidden, :input_html => { :value => "verified" } %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Verify Funds", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>

      <%# when the job status is set to finished %> 
      <% elsif @job.status_finished? %>
        <h1>Send Payment: <%= @job.title %></h1>
        <%= f.input :successful, label: "This job completed successfully and on time!" %>
        <%= f.input :status, :as => :hidden, :input_html => { :value => "sent" } %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Pay Tradie", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>

      <%# when the job status is set to closed %>
      <% elsif @job.status_closed? %>
        <h1>Review Job: <%= @job.title %></h1>
        <p>Leave a review for the tradie that completed the job.</p>
        <%# need to add review logic here %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Submit Review", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>
      <% end %>
      
    <%# if the current user is a tradie %>
    <% elsif current_user.tradie %>
    
      <%# if the job status is open %>
      <% if @job.status_open? %>
        <h1>Submit Quote For: <%= @job.title %></h1>
        <p>Upload quote here. Don't forget to add your payment details in your quote.</p>
        <%= f.file_field :quote, class: "form-control" %>
        <%= f.input :price, required: true %>
        <%= f.input :payment_terms, collection: 7..30, required: true, label: 'Payment Terms (default: 7 days to make payment once job is completed)' %>
        <%= f.input :status, :as => :hidden, :input_html => { :value => "active" } %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Submit Quote", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>

      <%# if the job status is verified %>
      <% elsif @job.status_verified? %>
        <h1>Complete Job: <%= @job.title %></h1>
        <p>Upload photos of the completed job here</p>
        <%# change this to "completion_photos" later so that i can display only completion photos in the public card view %>
        <%= f.file_field :completion_photos, multiple: true, accept: "image/png, image/jpg, image/jpeg, image/pdf", class: "form-control" %>
        <%= f.input :status, :as => :hidden, :input_html => { :value => "finished" } %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Complete Job", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>

      <%# if the job status is sent %>
      <% elsif @job.status_sent? %>
        <h1>Payment Received: <%= @job.title %></h1>
        <%= f.input :paid_on_time, label: "Homeonwer paid within the agreed payment terms of #{@job.payment_terms} days!" %>
        <p><strong>By confirming that payment has been received, the job will be closed and you and the job owner will be able to leave a review of the job.</strong></p>
        <%= f.input :status, :as => :hidden, :input_html => { :value => "closed" } %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Payment Received", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>

      <%# if the job status is closed %>
      <% elsif @job.status_closed? %>
        <h1>Review Job: <%= @job.title %></h1>
        <p>Leave a review for the job owner that published the job.</p>
        <%# need to add review logic here %>
        <br>
        <div class="form-actions">
          <%= f.button :submit, label: "Submit Review", class: "btn btn-outline-success btn-md" %>
          <%= link_to 'Back', jobs_path, class: "btn btn-outline-dark btn-md" %>
        </div>
      <% end %>
    <% end %>
<% end %>

app/views/jobs/edit.html.erb
<%= render 'form', job: @job %>
<br>

app/views/jobs/index.html.erb
<h1>My Jobs</h1>
<% @jobs.each do |job| %>
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary">$<%= job.price.to_i %></strong>
      <h4 class="mb-0"><%= job.title %></h4>
      <div class="mb-1 text-muted">Payment Terms: <%= job.payment_terms %> days</div>
      <p class="card-text mb-auto"><%= job.full_address %></p>
      <p class="card-text mb-auto">
        <span class="badge bg-warning rounded-pill"><%= job.status %></span>
        <span class="badge bg-success rounded-pill"><%= "Successfully Completed" if job.successful? %></span>
        <span class="badge bg-success rounded-pill"><%= "Paid on Time" if job.paid_on_time %></span>
      </p>
      <div class="mb-1">
        <%= link_to "View Job", job_path(job.id), class:"btn btn-outline-primary" %>
        <%# if job status is open and the user is not a tradie %>
        <% if job.status_open? && !current_user.tradie? %>
          <%= link_to 'Edit Job', edit_job_path(job), class: "btn btn-outline-primary btn-md" %>
          <%= link_to 'Delete Job', job, method: :delete, data: { confirm: 'Are you sure? All information associated with this job will be deleted including anything a tradie may have uploaded. This can not be undone' }, class: "btn btn-danger btn-md" %>
        <%# if job status is active or verified %>
        <% elsif job.status_active? || job.status_verified? %>
          <%= link_to 'Cancel Job', update_job_path(job, status: "cancelled"), method: :patch, data: { confirm: 'Are you sure? This will cancel the job permanently. This does not null any prior agreements made with the other party. This can not be undone' }, class: "btn btn-outline-warning btn-md" %>
        <% end %>
      </div>
    </div>
    <div class="col-auto d-none d-lg-block">
      <%# if job has photos attached %>
      <% if job.photos.attached? %>
        <%# display the first photo %>
        <%= image_tag job.photos.first, class: "bd-placeholder-img", width: "350", height: "250" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/jobs/new.html.erb
<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<%# display public job show page %>
<%= render 'shared/public_show' %> 
<% if @job.status_closed? %>
  <h3>Reviews:</h3>
  <%# alternative way to render a partial from the shared folder and pass the reviews %>
  <%# <%= render 'shared/review', reviews: @job.reviews %>
  <%# render job reviews %>
  <% if @job.reviews.empty? %>
    <p>No reviews have been left for this job yet.</p>
  <% else %>
    <%= render @job.reviews %><br>
  <% end %>
  <%# if user has left 0 reviews for this job %>
  <% if @user_reviews == 0 %>
    <%= link_to 'Add Review', new_job_review_path(@job), class: "btn btn-outline-primary btn-md my-2" %>
  <% end %>
<% end %>
<%# check if user is signed in %>
<% if user_signed_in? %>
  <%# check if current user is the job homeowner or tradie %>
  <% if current_user.id == @job.homeowner_id || current_user.id == @job.tradie_id %>
    <%# if job status is cancelled %>
    <% if @job.status_cancelled? %>
      <p><strong>This job was cancelled</strong>
    <% else %>
      <%# display job progress partial %>
      <%= render "shared/job_progress" %><br>
    <% end %>
    <%# display job accordion %>
    <%= render "shared/job_accordion" %>
    <%# if the job status is closed %>
  <% end %>
  <%# check if current user is the job homeowner and if the job is open %>
  <% if current_user.id == @job.homeowner_id && @job.status_open? %>
    <%= link_to 'Edit Job', edit_job_path(@job), class: "btn btn-outline-primary btn-md" %>
    <%= link_to 'Back', :back, class: "btn btn-outline-dark btn-md" %><br>
  <%# check if current user is the job tradie and if the job is open %>
  <% elsif current_user.tradie && @job.status_open? %>
    <%= link_to 'Submit Quote', edit_job_path(@job), class: "btn btn-outline-primary btn-md" %>
    <%= link_to 'Back', :back, class: "btn btn-outline-dark btn-md" %><br>
  <% else %>
    <%= link_to 'Back', :back, class: "btn btn-outline-dark btn-md" %><br>
  <% end %>
<% else %>
  <%= link_to 'Back', :back, class: "btn btn-outline-dark btn-md" %><br>
<% end %>