config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  root 'home#page'
  patch '/jobs/:id/update', to: 'jobs#update_job', as: 'update_job'
  resources :jobs do
    resources :reviews
  end
  devise_for :users
  get '/profile/:id', to: 'profile#page', as: 'profile_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_job_accordion.html.erb
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <h4>Job Info</h4>
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p><strong>Address: </strong><%= @job.full_address %></p>
                <p><strong>Price: </strong>$<%= @job.price.to_i %></p>
                <p><strong>Payment terms: </strong><%= @job.payment_terms %> days</p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <h4>Job Photos</h4>
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
            <% if @job.photos.attached? %>
                <% @job.photos.each do |photo| %>
                <%= image_tag photo, class: "d-block w-100", width: "100%", height: "450" %>
                <% end %>
            <% end %>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            <h4>Quote</h4>
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
            <div class="accordion-body">
            <% if @job.quote.attached? %>
                <%= image_tag @job.quote, class: "d-block w-100" %>
            <% end %>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingFour">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            <h4>Completion Photos</h4>
            </button>
        </h2>
        <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
            <div class="accordion-body">
            <% if @job.completion_photos.attached? %>
                <% @job.completion_photos.each do |photo| %>
                <%= image_tag photo, class: "d-block w-100", width: "100%", height: "450" %>
                <% end %>
            <% end %>
            </div>
        </div>
    </div>
</div>
<br>

app/views/shared/_job_progress.html.erb
<div class="list-group">

    <%# submit quote step %>
    <% if @job.status_open? %>
        <li class="list-group-item list-group-item-action list-group-item-primary">
        <span class="badge bg-primary rounded-pill">In Progress</span> Quote Submitted
        <%# may not need this button as the tradie always sees a different submit quote button %>
        <%# <span class="progress_button"><%= link_to 'Submit Quote', edit_job_path(@job), class: "btn btn-outline-primary btn-sm" %>
        </li>
    <% else %>
        <li class="list-group-item list-group-item-action list-group-item-success">
        <span class="badge bg-success rounded-pill">
            Completed 
        </span> Quote Submitted</span>
        </li>
    <% end%>

    <%# funds verified step %>
    <% if @job.status_open? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> PayProof Funds Verification
        </li>
    <% elsif @job.status_active? %>
        <li class="list-group-item list-group-item-action list-group-item-primary">
        <span class="badge bg-primary rounded-pill">In Progress</span> PayProof Funds Verification 
        <% if current_user.id == @job.homeowner_id %>
          <span class="progress_button"><%= link_to 'Verify Funds', edit_job_path(@job), class: "btn btn-outline-primary btn-sm" %></span>
        <% end %>
        </li>
    <% else %>
        <li class="list-group-item list-group-item-action list-group-item-success">
        <span class="badge bg-success rounded-pill">Completed</span> PayProof Funds Verification</span>
        </li>     
    <% end%>

    <%# job finished step %>
    <% if @job.status_open? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Job Finished
        </li>      
    <% elsif @job.status_active? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Job Finished
        </li>  
    <% elsif @job.status_verified?  %>
        <li class="list-group-item list-group-item-action list-group-item-primary">
        <span class="badge bg-primary rounded-pill">In Progress</span> Job Finished 
        <% if current_user.id == @job.tradie_id %>
          <span class="progress_button"><%= link_to 'Job Completed', edit_job_path(@job), class: "btn btn-outline-primary btn-sm" %></span>
        <% end %>
        </li>  
    <% else %>
        <li class="list-group-item list-group-item-action list-group-item-success">
        <span class="badge bg-success rounded-pill">Completed</span> Job Finished 
        </li>      
    <% end%>

    <%# payment sent step %>
    <% if @job.status_open? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Sent 
        </li>      
    <% elsif @job.status_active? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Sent 
        </li>  
    <% elsif @job.status_verified? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Sent 
        </li>  
    <% elsif @job.status_finished? %>
        <li class="list-group-item list-group-item-action list-group-item-primary">
        <span class="badge bg-primary rounded-pill">In Progress</span> Payment Sent 
        <% if current_user.id == @job.homeowner_id %>
          <span class="progress_button"><%= link_to 'Pay Tradie', edit_job_path(@job), class: "btn btn-outline-primary btn-sm" %></span>
        <% end %>
    <% else %>
        <li class="list-group-item list-group-item-action list-group-item-success">
        <span class="badge bg-success rounded-pill">Completed</span> Payment Sent 
        </li>      
    <% end%>

    <%# payment received step %>
    <% if @job.status_open? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Received
        </li>      
    <% elsif @job.status_active? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Received
        </li>
    <% elsif @job.status_verified? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Received
        </li>
    <% elsif @job.status_finished? %>
        <li class="list-group-item list-group-item-action list-group-item-secondary">
        <span class="badge bg-secondary rounded-pill">Waiting</span> Payment Received
        </li>
    <% elsif @job.status_sent? %>
        <li class="list-group-item list-group-item-action list-group-item-primary">
        <span class="badge bg-primary rounded-pill">In Progress</span> Payment Received 
        <% if current_user.id == @job.tradie_id %>
          <span class="progress_button"><%= link_to 'Payment Received', edit_job_path(@job), class: "btn btn-outline-primary btn-sm" %></span>
        <% end %>
        </li>
    <% else %>
        <li class="list-group-item list-group-item-action list-group-item-success">
        <span class="badge bg-success rounded-pill">Completed</span> Payment Received
        </li>      
    <% end%>

</div>

 

app/views/shared/_navbar.html.erb
<nav class="navbar-light bg-light">
  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4">

        <%= link_to "PayProof", root_path, class: "navbar-brand d-flex align-items-center col-md-3 mb-2 mb-md-0" %>


      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">

        <div class="container-fluid justify-content-center">
        <%= simple_form_for :search_term, url: root_path, method: "GET", html: { class: 'form-control me-2' } do |f| %>
          <%= f.input :suburb, label: false, placeholder: "enter suburb", input_html: {value: ""} %> 
        <% end %>
        </div>

      </ul>


      <div class="col-md-3 text-end nav-item dropdown">
      <ul class="navbar-nav align-items-center">
      <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="/" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.profile_pic.attached? %>
                <%= image_tag current_user.profile_pic, class: "rounded-circle", style: "width: 32px; height: 32px;" %>
              <% else %>
                <img src="https://www.pngitem.com/pimgs/m/78-786293_1240-x-1240-0-avatar-profile-icon-png.png" alt="mdo" width="32" height="32" class="rounded-circle">
              <% end %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
              <li class="nav-item">
                  <%= link_to "Home", root_path, class: "dropdown-item" %>
              </li>
              <li class="nav-item">
                  <% if user_signed_in? %>
                    <%= link_to "@#{current_user.username}", profile_page_path(current_user.id), class: "dropdown-item" %>
                  <% end %>
              </li>
              <% if user_signed_in? && !current_user.tradie? %>
                <li class="nav-item">
                  <%= link_to 'New Job', new_job_path, class: "dropdown-item" %>
                </li>
              <% end %>
              <li class="nav-item">
                  <%= link_to "My Jobs", jobs_path, class: "dropdown-item" %>
              </li>
              <li class="nav-item">
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
              <% else %>
          <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary" %>
          </li>
        <% end %>
      </li>
      </ul>
      </div>
      </ul>
    </header>
  </div>
</nav>

app/views/shared/_public_card.html.erb
<div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <div class="col p-4 d-flex flex-column position-static">
    <strong class="d-inline-block mb-2 text-primary"><%= job.suburb.capitalize %></strong>
    <h4 class="mb-0"><%= job.title %></h4>
    <p class="card-text mb-auto overflow-hidden"><%= job.description %></p>
    <div class="mb-1">
      <% if job.status_open? %>
        <span class="badge bg-warning rounded-pill"><%= job.status %></span>
        <span class="badge bg-primary rounded-pill">Taking quotes!</span>
      <% elsif job.status_sent? || job.status_closed? %>
        <span class="badge bg-success rounded-pill"><%= "Successfully Completed" if job.successful? %></span>
        <span class="badge bg-success rounded-pill"><%= "Paid on Time" if job.paid_on_time %></span>
      <% end %>
    </div>
    <div class="mb-1 py-1">
      <%= link_to "View Job", job_path(job.id), class:"btn btn-outline-primary" %>
    </div>
  </div>
  <div class="col-auto d-none d-lg-block">
    <% if job.photos.attached? %>
      <%= image_tag job.photos.first, class: "bd-placeholder-img", width: "350", height: "250" %>
    <% end %>
  </div>
</div>

app/views/shared/_public_show.html.erb
<h1><%= @job.title %></h1>
<hr>
<h4>
    <%# if homeonwer has profile pic %>
    <% if @job.homeowner.profile_pic.attached? %>
        <%= image_tag @job.homeowner.profile_pic, class: "rounded-circle", style: "width: 48px; height: 48px;" %>
    <% else %>
        <img src="https://www.pngitem.com/pimgs/m/78-786293_1240-x-1240-0-avatar-profile-icon-png.png" alt="mdo" width="48" height="48" class="rounded-circle">
    <% end %> 
    <%= link_to "@#{@job.homeowner.username}", profile_page_path(@job.homeowner.id), style: "text-decoration: none;" %> - Job Owner
</h4>
<%# if job has a tradie %>
<% if @job.tradie_id? %>
    <h4>
        <%# if tradie has profile pic %>
        <% if @job.tradie.profile_pic.attached? %>
            <%= image_tag @job.tradie.profile_pic, class: "rounded-circle", style: "width: 48px; height: 48px;" %>
        <% else %>
            <img src="https://www.pngitem.com/pimgs/m/78-786293_1240-x-1240-0-avatar-profile-icon-png.png" alt="mdo" width="48" height="48" class="rounded-circle">
        <% end %> 
        <%= link_to "@#{@job.tradie.username}", profile_page_path(@job.tradie.id), style: "text-decoration: none;" %> - Tradesman
    </h4>
<% end %>
<hr>
<h4><strong><%= @job.suburb %>, <%= @job.state %></strong></h4>
<h5>
<span class="badge bg-warning rounded-pill"><%= @job.status %></span>
<span class="badge bg-success rounded-pill"><%= "Successfully Completed" if @job.successful? %></span>
<span class="badge bg-success rounded-pill"><%= "Paid on Time" if @job.paid_on_time %></span>
</h5>
<%# carousel %>
<%# if job was successful %>
<% if @job.successful %>
    <div id="carousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
        <div class="carousel-inner">
        <%# if job has completion photos %>
        <% if @job.completion_photos.attached? %>
            <% @job.completion_photos.each_with_index do |photo, index| %>
                <div id="carousel_item_<%= index %>" class="carousel-item <%= index == 0 ? 'active' : '' %>">
                <%= image_tag photo, class: 'd-block w-100', width: "100%", height: "450" %><br>
                </div>
            <% end %>
        <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
<% else %>
    <div id="carousel" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
        <div class="carousel-inner">
        <% @job.photos.each_with_index do |photo, index| %>
            <div id="carousel_item_<%= index %>" class="carousel-item <%= index == 0 ? 'active' : '' %>">
            <%= image_tag photo, class: 'd-block w-100', width: "100%", height: "450" %><br>
            </div>
        <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
<% end %>
<hr><p><strong>Description: </strong><%= @job.description %></p><hr> 

app/views/shared/_review_form.html.erb
<%= simple_form_for([@job, @job.reviews.build]) do |f| %>
    <%= f.input :rating, required: true, collection: 1..5 %>
    <%= f.input :comment, required: true %>
    <%= f.button :submit, label: "Update Review", class: "btn btn-outline-success btn-md" %>
<% end %>