config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  root 'home#page'
  patch '/jobs/:id/update', to: 'jobs#update_job', as: 'update_job'
  resources :jobs do
    resources :reviews
  end
  devise_for :users
  get '/profile/:id', to: 'profile#page', as: 'profile_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_job
  before_action :find_review, only: %i[edit update destroy]
  before_action :check_ownership, only: %i[edit update destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # set the job id
    @review.job_id = @job.id
    # set the user id
    @review.user_id = current_user.id

    # redirect to job on successful review save
    if @review.save
      redirect_to job_path(@job), notice: 'Review was successfully created.'
    else
      render 'new', alert: 'Unable to create review.'
    end
  end

  def edit; end

  def update
    # redirect to job on successful review update
    if @review.update(review_params)
      redirect_to job_path(@job), notice: 'Review was successfully updated.'
    else
      render 'edit', alert: 'Unable to update review.'
    end
  end

  def destroy
    @review.destroy
    redirect_to job_path(@job), notice: 'Review was successfully deleted.'
  end

  private

  # sets allowable parameters
  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  # finds the job based on the job id parameter
  def find_job
    @job = Job.find(params[:job_id])
  end

  # finds the review based on the id paramters
  def find_review
    @review = Review.find(params[:id])
  end

  def check_ownership
    redirect_to root_url, alert: 'You do not have access to that review' if current_user.id != @review.user_id
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<%# alternative way to render the partial for reviews when in the shared folder %>
<%# <% reviews.each do |review| %>
    <%# <p><%= review.rating</p> %>
    <%# <p><%= review.comment</p> %>
<%# <% end %>

<div class="card text-center">
  <div class="card-body">
    <h4 class="card-title"><%= review.rating %>/5</h4>
    <blockquote class="blockquote mb-0">
      <p><em>"<%= review.comment %>"</em></p>
    </blockquote>
    <p class="card-text p-2">
      <%# if reviewer has a profile pic %>
      <% if review.user.profile_pic.attached? %>
        <%= image_tag review.user.profile_pic, class: "rounded-circle", style: "width: 32px; height: 32px;" %>
      <% else %>
        <img src="https://www.pngitem.com/pimgs/m/78-786293_1240-x-1240-0-avatar-profile-icon-png.png" alt="mdo" width="32" height="32" class="rounded-circle">
      <% end %> 
      <%= link_to "@#{review.user.username}", profile_page_path(review.user.id), style: "text-decoration: none;" %>
    </p>
    <%# if user signed in and current user published the review %>
    <% if user_signed_in? && review.user_id == current_user.id %>
      <%= link_to 'Edit Review', edit_job_review_path(review.job, review), class: "btn btn-outline-primary btn-sm" %>
      <%= link_to 'Delete Review', job_review_path(review.job, review), method: :delete, data: {confirm: "Are you sure you want to delete this review?"}, class: "btn btn-danger btn-sm" %>
    <% end %>
  </div>
</div><br>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= simple_form_for([@job, @review]) do |f| %>
    <%= f.input :rating, required: true, collection: 1..5 %>
    <%= f.input :comment, required: true %>
    <%= f.button :submit, label: "Update Review", class: "btn btn-outline-success btn-md" %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add Review</h1>

<%= render 'shared/review_form' %>